chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
  path('room/<int:course_id>/', views.course_chat_room, name='course_chat_room'),
]

project/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from accounts.views import logout_view
from courses.views import CourseListView

urlpatterns = [
  path("admin/", admin.site.urls),
  # path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
  path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
  path('accounts/logout/', logout_view, name='logout'),
  path('course/', include('courses.urls')),
  path('students/', include('students.urls')),
  path('api/', include('courses.api.urls', namespace='api')),
  path('chat/', include('chat.urls', namespace='chat')),
  path("__reload__/", include("django_browser_reload.urls")),
  path('__debug__/', include('debug_toolbar.urls')),
  path('', CourseListView.as_view(), name='course_list'),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.views.decorators.cache import cache_page
from django.urls import path
from . import views

urlpatterns = [
  path('register/', views.StudentRegistrationView.as_view(), name='student_registration'),
  path('enroll-course/', views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
  path('courses/', views.StudentCourseListView.as_view(), name='student_course_list'),
  path('course/<pk>/', cache_page(60 * 15)(views.StudentCourseDetailView.as_view()), name='student_course_detail'),
  path('courses/<pk>/<module_id>/', cache_page(60 * 15)(views.StudentCourseDetailView.as_view()), name='student_course_detail_module'),
]

students/forms.py
from django import forms
from courses.models import Course


class CourseEnrollForm(forms.Form):
  course = forms.ModelChoiceField(queryset=Course.objects.all(), widget=forms.HiddenInput)

students/views.py
from django.views.generic.edit import CreateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from .forms import CourseEnrollForm
from courses.models import Course


class StudentRegistrationView(CreateView):
  template_name = 'students/student/registration.html'
  form_class = UserCreationForm
  success_url = reverse_lazy('student_course_list')

  def form_valid(self, form):
    result = super().form_valid(form)
    cd = form.cleaned_data
    user = authenticate(username=cd['username'], password=['password1'])
    login(self.request, user)
    return result


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
  course = None
  form_class = CourseEnrollForm

  def form_valid(self, form):
    self.course = form.cleaned_data['course']
    self.course.students.add(self.request.user)
    return super().form_valid(form)

  def get_success_url(self):
    return reverse_lazy('student_course_detail', args=[self.course.id])


class StudentCourseListView(LoginRequiredMixin, ListView):
  model = Course
  template_name = 'students/course/list.html'

  def get_queryset(self):
    qs = super().get_queryset()
    return qs.filter(students__in=[self.request.user])


class StudentCourseDetailView(DetailView):
  model = Course
  template_name = 'students/course/detail.html'

  def get_queryset(self):
    qs = super().get_queryset()
    return qs.filter(students__in=[self.request.user])

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    # * get Course object
    course = self.get_object()
    if 'module_id' in self.kwargs:
      # * get current module
      context['module'] = course.modules.get(id=self.kwargs['module_id'])
    else:
      # * get the first module
      context['module'] = course.modules.all()[0]
    return context

templates/students/course/detail.html
{% extends "base.html" %}
{% load cache %}
{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
  <h1 class="title-1">{{ object.title }}</h1>
  <br>
  <div class="my-split">
    <div class="sidebar">
      <h3 class="title-2">Modules</h3>
      <br>
      <ul id="modules">
        {% for m in object.modules.all %}
          <li data-id="{{ m.id }}" {% if m == module %}class="selected"{% endif %}>
              <a href="{% url "student_course_detail_module" object.id m.id %}">
                <span>
                  Module <span class="order">{{ m.order|add:1 }}</span>
                </span>
                <br>
                {{ m.title }}
              </a>
          </li>
        {% empty %}
          <br>
          <li class="title-3">No modules yet.</li>
        {% endfor %}
        <li>
          <a href="{% url "chat:course_chat_room" object.id %}" class="success-btn">Course chat room</a>
        </li>
      </ul>
    </div>

    <div class="text-center">
      {% cache 600 module_contents module %}
        {% for content in module.contents.all %}
          <div class="item">
            {% with item=content.item %}
              <h2 class="title-3">{{ item.title }}</h2>
              <br>
              <div>
                {{ item.render }}
              </div>
            {% endwith %}
          </div>
        {% endfor %}
      {% endcache %}
    </div>

  </div>
{% endblock content %}

templates/students/course/list.html
{% extends "base.html" %}

{% block title %}My courses{% endblock title %}

{% block content %}
  <h1 class="title-1">My courses</h1>
  <br>
  <div>
    {% for course in object_list %}
      <div>
        <h3 class="title-2">{{ course.title }}</h3>
        <p><a href="{% url "student_course_detail" course.id %}" class="btn">Access contents</a></p>
        <br>
        <hr>
      </div> 
    {% empty %}
      <p>
        You are not enrolled in any courses yet.
        <a href="{% url "course_list" %}" class="link">Browse courses</a> 
        to enroll on a course.
      </p>
    {% endfor %}
  </div>
{% endblock content %}